# Jonathan's gh config
#
version: 1
git_protocol: https
editor: nvim
prompt: enabled
pager: cat
aliases:
  co: pr checkout
  mycreate: repo create --private --add-readme --clone
http_unix_socket:
browser: /Applications/Zen.app/Contents/MacOS/zen
color_labels: enabled
